exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3

## If like to embrace black styles even in the docs:
# - repo: https://github.com/asottile/blacken-docs
#   rev: v1.13.0
#   hooks:
#   - id: blacken-docs
#     additional_dependencies: [black]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.261
  hooks:
  - id: ruff

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    entry: env MYPYPATH=src mypy
    args: []
    additional_dependencies:
    - bleak>=0.20.0
    - bluetooth-adapters>=0.16.1; python_version>="3.9"
    - bluetooth-numbers
    - rich
    - textual>=0.14.0
